agent: "MASAC"  # the learning algorithms_marl
env_name: "Drones"
env_id: "MultiHoverAviary"
obs_type: 'kin'
act_type: 'vel'
num_drones: 3
record: False
obstacles: True
max_episode_steps: 2500
render: False
sleep: 0.01
learner: "MASAC_Learner"
policy: "Gaussian_MASAC_Policy"
representation: "Basic_Identical"
vectorize: "DummyVecMultiAgentEnv"
runner: "MARL"
on_policy: False

representation_hidden_size: []  # the units for each hidden layer
actor_hidden_size: [256, 256]
critic_hidden_size: [256, 256]
activation: 'leaky_relu'
activation_action: 'tanh'
use_parameter_sharing: True
use_actions_mask: False

seed: 1
parallels: 10
buffer_size: 1000000
batch_size: 1024
learning_rate_actor: 0.001  # learning rate for actor
learning_rate_critic: 0.001  # learning rate for critic
gamma: 0.99  # discount factor
tau: 0.005  # soft update for target networks
alpha: 0.01
use_automatic_entropy_tuning: True

start_training: 2000  # start training after n episodes
running_steps: 20000000
training_frequency: 1

use_grad_clip: True
grad_clip_norm: 0.5

eval_interval: 100000
test_episode: 5

log_dir: "./logs/masac/"
model_dir: "./models/masac/"
